# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 07:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cacher',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=4096)),
                ('content', models.FileField(upload_to='cache_dir')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('cache_time', models.DurationField(default=datetime.timedelta(0, 60))),
                ('enabled', models.BooleanField(default=True)),
                ('force_update', models.BooleanField(default=False)),
                ('status', models.CharField(default='OK', max_length=2)),
                ('status_comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
