# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('secure_proxy', '0003_auto_20171107_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='cacher',
            name='issuer',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='secure_proxy.Issuer'),
        ),
    ]
