# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secure_proxy', '0005_auto_20171107_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cacher',
            options={'ordering': ['-created'], 'permissions': [('can_invalidate', 'Can force invalidation')]},
        ),
    ]
