# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('secure_proxy', '0006_auto_20171107_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuer',
            name='secret',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='issuer',
            name='secure',
            field=models.BooleanField(default=True),
        ),
    ]
