# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-12 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_proxy', '0007_auto_20171108_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='cacher',
            name='expect_http_200',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cacher',
            name='retries_limit',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
